package com.fatec.neweducation.model;
// Generated 25/08/2014 21:45:35 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Game generated by hbm2java
 */
public class Game  implements java.io.Serializable {


     private Integer id;
     private Date date;
     private Integer fkPlayerSchoolGrade;
     private Integer fkQuestionGame;
     private Boolean isCorrectAnswer;

    public Game() {
    }

    public Game(Date date, Integer fkPlayerSchoolGrade, Integer fkQuestionGame, Boolean isCorrectAnswer) {
       this.date = date;
       this.fkPlayerSchoolGrade = fkPlayerSchoolGrade;
       this.fkQuestionGame = fkQuestionGame;
       this.isCorrectAnswer = isCorrectAnswer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getFkPlayerSchoolGrade() {
        return this.fkPlayerSchoolGrade;
    }
    
    public void setFkPlayerSchoolGrade(Integer fkPlayerSchoolGrade) {
        this.fkPlayerSchoolGrade = fkPlayerSchoolGrade;
    }
    public Integer getFkQuestionGame() {
        return this.fkQuestionGame;
    }
    
    public void setFkQuestionGame(Integer fkQuestionGame) {
        this.fkQuestionGame = fkQuestionGame;
    }
    public Boolean getIsCorrectAnswer() {
        return this.isCorrectAnswer;
    }
    
    public void setIsCorrectAnswer(Boolean isCorrectAnswer) {
        this.isCorrectAnswer = isCorrectAnswer;
    }




}


