package com.fatec.neweducation.model;
// Generated 25/08/2014 21:45:35 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.FetchMode;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;

/**
 * Game generated by hbm2java
 */
@Entity
@Table(name = "game")
public class Game  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "date")
    private Date date;

    @Column(name = "fk_player_school_grade")
    private PlayerSchoolGrade fkPlayerSchoolGrade;

    @Column(name = "fk_question")
    private Question fkQuestionGame;

    @Column(name = "is_correct_answer")
     private Boolean isCorrectAnswer;

    public Game() {
    }

    public Game(Date date, PlayerSchoolGrade fkPlayerSchoolGrade, Question fkQuestionGame, Boolean isCorrectAnswer) {
       this.date = date;
       this.fkPlayerSchoolGrade = fkPlayerSchoolGrade;
       this.fkQuestionGame = fkQuestionGame;
       this.isCorrectAnswer = isCorrectAnswer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public PlayerSchoolGrade getFkPlayerSchoolGrade() {
        return this.fkPlayerSchoolGrade;
    }
    
    public void setFkPlayerSchoolGrade(PlayerSchoolGrade fkPlayerSchoolGrade) {
        this.fkPlayerSchoolGrade = fkPlayerSchoolGrade;
    }
    public Question getFkQuestionGame() {
        return this.fkQuestionGame;
    }
    
    public void setFkQuestionGame(Question fkQuestionGame) {
        this.fkQuestionGame = fkQuestionGame;
    }
    public Boolean getIsCorrectAnswer() {
        return this.isCorrectAnswer;
    }
    
    public void setIsCorrectAnswer(Boolean isCorrectAnswer) {
        this.isCorrectAnswer = isCorrectAnswer;
    }




}


