package com.fatec.neweducation.model;
// Generated 25/08/2014 21:45:35 by Hibernate Tools 3.6.0


import com.fatec.neweducation.model.resources.Gender;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Player generated by hbm2java
 */
@Entity
@Table(name = "player")
public class Player  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "fk_user")
    private User fkUser;

    @Column(name = "date_of_birth")
    private Date dateOfBirth;

    @Column(name = "gender")
    @Enumerated(EnumType.STRING)
    private Gender gender;

    public Player() {
    }

    public Player(User fkUser, Date dateOfBirth, Gender gender) {
       this.fkUser = fkUser;
       this.dateOfBirth = dateOfBirth;
       this.gender = gender;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getFkUser() {
        return this.fkUser;
    }
    
    public void setFkUser(User fkUser) {
        this.fkUser = fkUser;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public Gender getGender() {
        return this.gender;
    }
    
    public void setGender(Gender gender) {
        this.gender = gender;
    }




}


