package com.fatec.neweducation.model;
// Generated 25/08/2014 21:45:35 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;




/**
 * PlayerSchoolGrade generated by hbm2java
 */
@Entity
@Table(name = "player_school_grade")
public class PlayerSchoolGrade  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "year_classe")
    private Integer yearClasse;

    @Column(name = "classe")
    private Integer classe;

    @Column(name = "fk_player")
    private Player fkPlayer;

    @Column(name = "fk_school")
    private School fkSchool;

    public PlayerSchoolGrade() {
    }

    public PlayerSchoolGrade(Integer yearClasse, Integer classe, Player fkPlayer, School fkSchool) {
       this.yearClasse = yearClasse;
       this.classe = classe;
       this.fkPlayer = fkPlayer;
       this.fkSchool = fkSchool;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getYearClasse() {
        return this.yearClasse;
    }
    
    public void setYearClasse(Integer yearClasse) {
        this.yearClasse = yearClasse;
    }
    public Integer getClasse() {
        return this.classe;
    }
    
    public void setClasse(Integer classe) {
        this.classe = classe;
    }
    public Player getFkPlayer() {
        return this.fkPlayer;
    }
    
    public void setFkPlayer(Player fkPlayer) {
        this.fkPlayer = fkPlayer;
    }
    public School getFkSchool() {
        return this.fkSchool;
    }
    
    public void setFkSchool(School fkSchool) {
        this.fkSchool = fkSchool;
    }




}


