package com.fatec.neweducation.model;
// Generated 23/08/2014 14:33:20 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Player generated by hbm2java
 */
public class Player  implements java.io.Serializable {


     private Integer id;
     private Integer fkUser;
     private Date dateOfBirth;
     private String gender;

    public Player() {
    }

    public Player(Integer fkUser, Date dateOfBirth, String gender) {
       this.fkUser = fkUser;
       this.dateOfBirth = dateOfBirth;
       this.gender = gender;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getFkUser() {
        return this.fkUser;
    }
    
    public void setFkUser(Integer fkUser) {
        this.fkUser = fkUser;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }




}


