package com.fatec.neweducation.model;
// Generated 25/08/2014 21:45:35 by Hibernate Tools 3.6.0



/**
 * Question generated by hbm2java
 */
public class Question  implements java.io.Serializable {


     private Integer id;
     private Integer typeQuestion;
     private String hability;
     private String asking;
     private Integer level;

    public Question() {
    }

    public Question(Integer typeQuestion, String hability, String asking, Integer level) {
       this.typeQuestion = typeQuestion;
       this.hability = hability;
       this.asking = asking;
       this.level = level;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getTypeQuestion() {
        return this.typeQuestion;
    }
    
    public void setTypeQuestion(Integer typeQuestion) {
        this.typeQuestion = typeQuestion;
    }
    public String getHability() {
        return this.hability;
    }
    
    public void setHability(String hability) {
        this.hability = hability;
    }
    public String getAsking() {
        return this.asking;
    }
    
    public void setAsking(String asking) {
        this.asking = asking;
    }
    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }




}


