package com.fatec.neweducation.model;
// Generated 25/08/2014 21:45:35 by Hibernate Tools 3.6.0

import com.fatec.neweducation.model.resources.Hability;
import com.fatec.neweducation.model.resources.TypeQuestion;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question")
public class Question  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "type_question")
    @Enumerated(EnumType.ORDINAL)
    private TypeQuestion typeQuestion;

    @Column(name = "hability")
    @Enumerated(EnumType.STRING)
    private Hability hability;

    @Column(name = "asking")
    private String asking;

    @Column(name = "level")
     private Integer level;

    public Question() {
    }

    public Question(TypeQuestion typeQuestion, Hability hability, String asking, Integer level) {
       this.typeQuestion = typeQuestion;
       this.hability = hability;
       this.asking = asking;
       this.level = level;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TypeQuestion getTypeQuestion() {
        return this.typeQuestion;
    }
    
    public void setTypeQuestion(TypeQuestion typeQuestion) {
        this.typeQuestion = typeQuestion;
    }
    public Hability getHability() {
        return this.hability;
    }
    
    public void setHability(Hability hability) {
        this.hability = hability;
    }
    public String getAsking() {
        return this.asking;
    }
    
    public void setAsking(String asking) {
        this.asking = asking;
    }
    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }




}


