package com.fatec.neweducation.model;
// Generated 25/08/2014 21:45:35 by Hibernate Tools 3.6.0

import com.fatec.neweducation.model.resources.TypeUser;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "name_user")
    private String nameUser;

    @Column(name = "type_user")
    @Enumerated(EnumType.ORDINAL)
    private TypeUser typeUser;

    @Column(name = "login_user")
    private String loginUser;

    @Column(name = "password")
     private String password;

    public User() {
    }

    public User(String nameUser, TypeUser typeUser, String loginUser, String password) {
       this.nameUser = nameUser;
       this.typeUser = typeUser;
       this.loginUser = loginUser;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNameUser() {
        return this.nameUser;
    }
    
    public void setNameUser(String nameUser) {
        this.nameUser = nameUser;
    }
    public TypeUser getTypeUser() {
        return this.typeUser;
    }
    
    public void setTypeUser(TypeUser typeUser) {
        this.typeUser = typeUser;
    }
    public String getLoginUser() {
        return this.loginUser;
    }
    
    public void setLoginUser(String loginUser) {
        this.loginUser = loginUser;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


